export const translations = {
  "pt-br": {
      "lg-ptbr": "pt-br",
      "lg-eng": "Inglês",
      "lg-spn": "Espanhol",
      "item-desktop1": "Início",
      "item-desktop2": "Especialidades",
      "item-desktop3": "Sobre",
      "item-desktop4": "Projetos",
      "button-desktop": "Contato",
      "item-mobile1": "Início",
      "item-mobile2": "Especialidades",
      "item-mobile3": "Sobre",
      "item-mobile4": "Projetos",
      "button-mobile": "Contato", 
      "top-title": "O DESENVOLVIMENTO DE SISTEMAS PARA AJUDA E AUXÍLIO GERAL <span>.</span>",
      "top-message": `<p>Do que seria o programador se o mesmo não pudesse abstrair, utilizar a criatividade e inovação com o desejo de ajudar um aos outros?<br>Um programador, para mim, é como um arquiteto digital. Ele não apenas escreve linhas de código, mas constrói mundos virtuais a partir do nada. É alguém que vê padrões onde outros veem caos, que transforma problemas complexos em desafios estimulantes.<br>A magia está na capacidade de abstrair - é como ser capaz de ver o código como um idioma próprio e entender sua dança. A criatividade é a faísca que torna cada linha única, é o toque pessoal que transforma o código em algo mais do que uma simples sequência de instruções. E a inovação é o ímpeto constante de melhorar, de buscar novas maneiras de fazer as coisas, de criar algo revolucionário a partir do convencional.<br>Mas o que realmente impulsiona muitos programadores, incluindo a mim, é a ideia de fazer a diferença. É saber que cada linha de código pode melhorar a vida de alguém, simplificar tarefas, conectar pessoas ou resolver problemas complexos. É a busca incessante por ajudar, por contribuir para um mundo onde a tecnologia não é apenas uma ferramenta, mas uma força para o bem.<br>Assim, ser um programador não é apenas sobre habilidades técnicas, mas sobre um misto de paixão, criatividade e o desejo de causar um impacto positivo no mundo.</p>`,
      "contact": "Entre em contato",
      "title-specialties": "MINHAS <span>ESPECIALIDADES</span>",
      "backend-title": "Desenvolvimento BackEnd e de banco",
      "backend-desc": `Conhecimento de conexão de banco de dados NoSQL (Firebase) e SQL (MySQL, MariaDb, Postgresql) e em linguagens como PHP (com Laravel), Java (JavaFX, Swing e Conexão SQL), C# e Python, todos com uma compreensão altamente embassada da lógica de programação`,
      "frontend-title": "Desenvolvimento Web <br> e Client-Side",
      "frontend-desc": `Conhecimento intermediário <br> em HTML/CSS/JS e frameworks/bibliotecas<br>(Bootstrap,Materialize,React,Next[...])`,
      "edition-title": "Edição",
      "edition-desc": `Noção razoável de edições de imagens, cortes, remoção de background e derivados via Gimp`,
      "title-about": "MUITO PRAZER <span>SOU GUSTAVO PEREIRA</span>",
      "message-about": `Olá! Meu nome é Gustavo e sou um entusiasta do Desenvolvimento de Sistemas há cerca de 2 anos e tenho uma paixão por criar soluções tecnológicas que impactam positivamente as pessoas.<br>Como alguém que já estuda nessa área por um tempo razoável, tenho conhecimentos e experiências diversas, com interesse especialmente no Desenvolvimento de sites Web pelo HTML, JS e um pouco do CSS e na linguagem de servidor PHP.<br>Acredito firmemente que ser um programador vai além das habilidades técnicas; é sobre paixão, criatividade e o desejo de causar um impacto positivo. Estou constantemente em busca de desafios que me permitam contribuir para um mundo onde a tecnologia seja uma força para o bem.<br>Dessa forma, estou bem entusiasmado com as oportunidades de colaborar e criar soluções inovadoras que possam fazer a diferença para todos.`,
      "title-portfolio": "MEU PORTFOLIO",
      "metaverse-desc": "Metaverso",
      "other-desc": "Outros",
      "contact-me": "FALA <span> COMIGO </span>",
      "form-email": "Seu e-mail",
      "form-name": "Seu nome",
      "form-cell": "Seu celular",
      "form-message": "Sua mensagem",
      "form-submit": "ENVIAR",
      "other-top-title": "OUTROS <span>PROJETOS</span>",
      "other-top-desc": "Estão listados alguns dos pequenos projetos e atividades que eu fiz ao decorrer na Etec e também outras externas que demonstram alguns dos meus outros conhecimentos de programação além do Desenvolvimento Web, do mais novo ao mais antigo",
      "other-backend-desc": "C# (.NET), C, Java (SpringBoot, Maven, Eclipse, Swing, ), Kotlin() PHP (Laravel, PDO), Python (FastAPI), SQL (MySQL, PostGres, SQLite), NoSQL (Firebase,MongoDB), Node(Next, Express) e paradigmas de POO, TDD, etc.",
      "other-frontend-desc": "Conhecimento intermediário <br> HTML (Semântico), CSS(Bootstrap,Materialize,TailWind,SASS), JS Vanilla, Node (React,Vue)",
      "other-edition-title": "Outros",
      "other-edition-desc": "Conhecimento em Machine Learning (IA), edição, aplicativos (Pacote Office, Trello, Figma), Engenharia de Software, etc.",
      "other-projects-title": "PROJETOS",
      "other-projects-list": `<span>HTML,CSS,JS: </span> <a href="https://github.com/GustavoPereira-Dev/Hangman">Hangman</a> , <a href="https://github.com/GustavoPereira-Dev/AtividadeCSS3">Zoo Site</a><br><br><span>Node (NPM): </span> <a href="https://github.com/GustavoPereira-Dev/Projeto-Alura">Projeto-Alura</a>, <a href=""></a><br><br><span>PHP: </span> <a href="https://github.com/GustavoPereira-Dev/SPTransAPI-busSearch">Olho Vivo Bus Search</a>, <a href="https://github.com/GustavoPereira-Dev/digitalcep">Digital CEP</a>,  <a href="https://github.com/GustavoPereira-Dev/ProjCarrosPHP">Project Car</a>,<br><br><span>Python:</span> <a href="https://github.com/GustavoPereira-Dev/Bootcamp-Python-Vivo">Bootcamp-Vivo</a>, <a href="https://github.com/GustavoPereira-Dev/Exercs-Python">Exercícios de Python</a><br><br><span>C#: </span> <a href="https://github.com/GustavoPereira-Dev/trilha-net-teste-unitarios-desafio">Teste unitários</a>(usando Xunit), <a href="https://github.com/GustavoPereira-Dev/trilha-net-poo-desafio">OOP in CSharp</a>,<a href="https://github.com/GustavoPereira-Dev/trilha-net-fundamentos-desafio">Fundamentals</a><br><br><span>Java: </span> <a href="https://github.com/GustavoPereira-Dev/Bootcamp-Santander-2024-BackEnd-Java">Bootcamp Santander</a>, <a href="https://github.com/GustavoPereira-Dev/Atividades-Java-LP">Atividades LP</a>,  <a href="https://github.com/GustavoPereira-Dev/Projeto-Eletrodomesticos-Java">Projeto Eletrodosmésticos</a>,<a href="https://github.com/GustavoPereira-Dev/Projeto-OO-Java">Reino animal</a>, <a href="https://github.com/GustavoPereira-Dev/AtividadeJogoCorrida">Corrida de carro</a><br><br><span>Kotlin: </span> <a href="https://github.com/GustavoPereira-Dev/Navigation-Compose">Navigation Compose</a>, <a href="https://github.com/GustavoPereira-Dev/TaskTodayApp">TaskTodayApp</a>, <a href="https://github.com/GustavoPereira-Dev/Calculator-Jetpack-Compose">Calculadora Compose</a>,<a href="https://github.com/GustavoPereira-Dev/Learning-Jetback-Compose">Learning Compose</a>,<a href="https://github.com/GustavoPereira-Dev/Android-Aplication-Compose">Android Aplication</a>, <a href=""></a><br><br><span>Outros: </span> <a href="https://github.com/GustavoPereira-Dev/lab-natty-or-not">Fake Natty or not</a><a href="https://github.com/GustavoPereira-Dev/Generative-AI-In-Microsoft">Generative AI in Microsoft</a>, <a href="https://github.com/GustavoPereira-Dev/Cognitive-Search-in-Azure-ML">Cognitive Search</a>, <a href="https://github.com/GustavoPereira-Dev/Natural-Language-in-Azure-ML"> Natural Language Azure</a>,<a href="https://github.com/GustavoPereira-Dev/Computer-Vision-in-Azure-ML"> Computer Vision</a>, <a href="https://github.com/GustavoPereira-Dev/Machine-Learning-in-Azure-ML">Machine Learning</a>, <a href="https://github.com/GustavoPereira-Dev/dio-lab-open-source">Contribuições no Github</a>`,
  },
  "eng": {
      "lg-ptbr": "Brazilian Portuguese",
      "lg-eng": "English",
      "lg-spn": "Spanish",
      "item-desktop1": "Home",
      "item-desktop2": "Specialties",
      "item-desktop3": "About",
      "item-desktop4": "Projects",
      "button-desktop": "Contact",
      "item-mobile1": "Home",
      "item-mobile2": "Specialties",
      "item-mobile3": "About",
      "item-mobile4": "Projects",
      "button-mobile": "Contact",
      "top-title": "THE DEVELOPMENT OF SYSTEMS FOR HELP AND GENERAL ASSISTANCE <span>.</span>",
      "top-message": `<p>What would a programmer be like if he couldn't abstract, use creativity and innovation with the desire to help each other?<br>A programmer, for me, is like a digital architect. He doesn't just write lines of code, he builds virtual worlds from scratch. This is someone who sees patterns where others see chaos, who turns complex problems into exciting challenges.<br>The magic is in the ability to abstract - it's like being able to see code as a language of its own and understand its dance. Creativity is the spark that makes each line unique, it is the personal touch that turns code into something more than a simple sequence of instructions. And innovation is the constant drive to improve, to seek new ways of doing things, to create something revolutionary from the conventional.<br>But what really drives many programmers, including me, is the idea of making a difference. It's knowing that each line of code can improve someone's life, simplify tasks, connect people or solve complex problems. It is the incessant search to help, to contribute to a world where technology is not just a tool, but a force for good.<br>So, being a programmer is not just about technical skills, but about a mix of passion, creativity and the desire to make a positive impact on the world.</p>`,
      "contact": "Contact me",
      "title-specialties": "MY <span>SPECIALTIES</span>",
      "backend-title": "BackEnd development and Database",
      "backend-desc": `Knowledge of NoSQL (Firebase) and SQL (MySQL, MariaDb, Postgresql) database connections and languages such as PHP (with Laravel), Java (JavaFX, Swing and SQL Connection), C# and Python, all with a highly grounded understanding of programming logic.`,
      "frontend-title": "Web development <br> and Client-Side",
      "frontend-desc": `Intermediate knowledge <br> in HTML/CSS/JS and frameworks/libraries<br>(Bootstrap,Materialize,React,Next[...])`,
      "edition-title": "Edition",
      "edition-desc": `Reasonable understanding of image editing, cropping, background removal and derivatives via Gimp`,
      "title-about": "GREAT PLEASURE <span>I'M GUSTAVO PEREIRA</span>",
      "message-about": `Hello! My name is Gustavo and I have been a Systems Development enthusiast for about 2 years and have a passion for creating technological solutions that positively impact people.<br>As someone who has been studying this area for a reasonable amount of time, I have diverse knowledge and experience, with a particular interest in Web site development using HTML, JS and a bit of CSS and the PHP server language.<br>I firmly believe that being a programmer goes beyond technical skills; it's about passion, creativity and the desire to make a positive impact. I am constantly looking for challenges that allow me to contribute to a world where technology is a force for good.<br>Therefore, I am very excited about the opportunities to collaborate and create innovative solutions that can make a difference for everyone.`,
      "title-portfolio": "MY PORTFOLIO",
      "metaverse-desc": "Metaverse",
      "other-desc": "Others",
      "contact-me": "CONTACT <span> ME </span>",
      "form-email": "Your email",
      "form-name": "Your name",
      "form-cell": "Your cellphone number",
      "form-message": "Your message",
      "form-submit": "SUBMIT",
      "other-top-title": "OTHER <span>PROJECTS</span>",
      "other-top-desc": "Listed here are some of the small projects and activities I did during Etec and also other external ones that demonstrate some of my other programming knowledge beyond Web Development, from newest to oldest.",
      "other-backend-desc": "C# (.NET), C, Java (SpringBoot, Maven, Eclipse, Swing), Kotlin, PHP (Laravel, PDO), Python (FastAPI), SQL (MySQL, PostGres, SQLite), NoSQL (Firebase, MongoDB), Node (Next, Express) and paradigms of OOP, TDD, etc.",
      "other-frontend-desc": "Intermediate knowledge <br> HTML (Semantic), CSS (Bootstrap, Materialize, TailWind, SASS), Vanilla JS, Node (React, Vue)",
      "other-edition-title": "Others",
      "other-edition-desc": "Knowledge in Machine Learning (AI), editing, applications (Office Suite, Trello, Figma), Software Engineering, etc.",
      "other-projects-title": "PROJECTS",
      "other-projects-list": `<span>HTML,CSS,JS: </span> <a href="https://github.com/GustavoPereira-Dev/Hangman">Hangman</a> , <a href="https://github.com/GustavoPereira-Dev/AtividadeCSS3">Zoo Site</a><br><br><span>Node (NPM): </span> <a href="https://github.com/GustavoPereira-Dev/Projeto-Alura">Alura Project</a>, <a href=""></a><br><br><span>PHP: </span> <a href="https://github.com/GustavoPereira-Dev/SPTransAPI-busSearch">Olho Vivo Bus Search</a>, <a href="https://github.com/GustavoPereira-Dev/digitalcep">Digital CEP</a>,  <a href="https://github.com/GustavoPereira-Dev/ProjCarrosPHP">Project Car</a>,<br><br><span>Python:</span> <a href="https://github.com/GustavoPereira-Dev/Bootcamp-Python-Vivo">Bootcamp-Vivo</a>, <a href="https://github.com/GustavoPereira-Dev/Exercs-Python">Python Exercises</a><br><br><span>C#: </span> <a href="https://github.com/GustavoPereira-Dev/trilha-net-teste-unitarios-desafio">Unit Tests</a>(using Xunit), <a href="https://github.com/GustavoPereira-Dev/trilha-net-poo-desafio">OOP in CSharp</a>,<a href="https://github.com/GustavoPereira-Dev/trilha-net-fundamentos-desafio">Fundamentals</a><br><br><span>Java: </span> <a href="https://github.com/GustavoPereira-Dev/Bootcamp-Santander-2024-BackEnd-Java">Bootcamp Santander</a>, <a href="https://github.com/GustavoPereira-Dev/Atividades-Java-LP">LP Activities</a>,  <a href="https://github.com/GustavoPereira-Dev/Projeto-Eletrodomesticos-Java">Appliances Project</a>,<a href="https://github.com/GustavoPereira-Dev/Projeto-OO-Java">Animal Kingdom</a>, <a href="https://github.com/GustavoPereira-Dev/AtividadeJogoCorrida">Car Race</a><br><br><span>Kotlin: </span> <a href="https://github.com/GustavoPereira-Dev/Navigation-Compose">Navigation Compose</a>, <a href="https://github.com/GustavoPereira-Dev/TaskTodayApp">TaskTodayApp</a>, <a href="https://github.com/GustavoPereira-Dev/Calculator-Jetpack-Compose">Compose Calculator</a>,<a href="https://github.com/GustavoPereira-Dev/Learning-Jetback-Compose">Learning Compose</a>,<a href="https://github.com/GustavoPereira-Dev/Android-Aplication-Compose">Android Application</a>, <a href=""></a><br><br><span>Others: </span> <a href="https://github.com/GustavoPereira-Dev/lab-natty-or-not">Fake Natty or not</a><a href="https://github.com/GustavoPereira-Dev/Generative-AI-In-Microsoft">Generative AI in Microsoft</a>, <a href="https://github.com/GustavoPereira-Dev/Cognitive-Search-in-Azure-ML">Cognitive Search</a>, <a href="https://github.com/GustavoPereira-Dev/Natural-Language-in-Azure-ML"> Natural Language Azure</a>,<a href="https://github.com/GustavoPereira-Dev/Computer-Vision-in-Azure-ML"> Computer Vision</a>, <a href="https://github.com/GustavoPereira-Dev/Machine-Learning-in-Azure-ML">Machine Learning</a>, <a href="https://github.com/GustavoPereira-Dev/dio-lab-open-source">Github Contributions</a>`,
  },
  "spn": {
      "lg-ptbr": "Portugués Brasileño",
      "lg-eng": "Inglés",
      "lg-spn": "Español",
      "item-desktop1": "Inicio",
      "item-desktop2": "Especialidades",
      "item-desktop3": "Sobre",
      "item-desktop4": "Proyectos",
      "button-desktop": "Contacto",
      "item-mobile1": "Início",
      "item-mobile2": "Especialidades",
      "item-mobile3": "Sobre",
      "item-mobile4": "Proyectos",
      "button-mobile": "Contacto", 
      "top-title": "EL DESARROLLO DE SISTEMAS DE AYUDA Y ASISTENCIA GENERAL <span>.</span>",
      "top-message": `<p>¿Cómo sería un programador si no pudiera abstraer, usar la creatividad y la innovación con ganas? ¿para ayudarse mutuamente?<br>Un programador, para mí, es como un arquitecto digital. No se limita a escribir líneas de código, sino que construye mundos virtuales desde cero. Es alguien que ve patrones donde otros ven caos, que convierte problemas complejos en desafíos apasionantes.<br>La magia está en la capacidad de abstraer: es como poder ver el código como un lenguaje propio y comprender su danza. La creatividad es la chispa que hace que cada línea sea única, es el toque personal que convierte el código en algo más que una simple secuencia de instrucciones. Y la innovación es el impulso constante por mejorar, por buscar nuevas formas de hacer las cosas, por crear algo revolucionario a partir de lo convencional.<br>Pero lo que realmente impulsa a muchos programadores, incluido yo, es la idea de marcar la diferencia. Es saber que cada línea de código puede mejorar la vida de alguien, simplificar tareas, conectar personas o resolver problemas complejos. Es la búsqueda incesante de ayudar, de contribuir a un mundo donde la tecnología no sea sólo una herramienta, sino una fuerza para el bien.<br>Entonces, ser programador no se trata solo de habilidades técnicas, sino de una combinación de pasión, creatividad y el deseo de generar un impacto positivo en el mundo.</p>`,
      "contact": "Entre en contato",
      "title-specialties": "MIS <span>ESPECIALIDADES</span>",
      "backend-title": "Desarrollo de Back End y bases de datos.",
      "backend-desc": `Conhecimento de conexão de banco de dados NoSQL (Firebase) e SQL (MySQL, MariaDb, Postgresql) e em linguagens como PHP (com Laravel), Java (JavaFX, Swing e Conexão SQL), C# e Python, todos com uma compreensão altamente embassada da lógica de programação.`,
      "frontend-title": "Desarrolo de Web <br> y Client-Side",
      "frontend-desc": `Conocimientos intermedios <br> en HTML/CSS/JS y frameworks/bibliotecas<br>(Bootstrap,Materialize,React,Next[...])`,
      "edition-title": "Edição",
      "edition-desc": `Comprensión razonable de la edición, recorte, eliminación de fondos y derivados de imágenes a través de Gimp.`,
      "title-about": "MUCHO PLACER <span>SOY GUSTAVO PEREIRA</span>",
      "message-about": `¡Hola! Mi nombre es Gustavo y soy un entusiasta del Desarrollo de Sistemas desde hace aproximadamente 2 años y tengo pasión por crear soluciones tecnológicas que impacten positivamente a las personas.<br>Como alguien que ha estado estudiando esta área durante un tiempo razonable, tengo diversos conocimientos y experiencia, con un interés particular en el desarrollo de sitios web utilizando HTML, JS y un poco de CSS y el lenguaje de servidor PHP.<br>Creo firmemente que ser programador va más allá de las habilidades técnicas; se trata de pasión, creatividad y el deseo de generar un impacto positivo. Busco constantemente desafíos que me permitan contribuir a un mundo donde la tecnología es una fuerza para el bien.<br>Por lo tanto, estoy muy entusiasmado con las oportunidades de colaborar y crear soluciones innovadoras que puedan marcar la diferencia para todos.`,
      "title-portfolio": "MI PORTAFOLIO",
      "metaverse-desc": "Metaverso",
      "other-desc": "Otros",
      "contact-me": "HABLA <span> CONMIGO </span>",
      "form-email": "Su e-mail",
      "form-name": "Su nombre",
      "form-cell": "Tu telefono movil",
      "form-message": "Sua mensaje",
      "form-submit": "MANDAR",
      "other-top-title": "OTROS <span>PROYECTOS</span>",
      "other-top-desc": "Aquí se enumeran algunos de los pequeños proyectos y actividades que realicé durante Etec y también otros externos que demuestran algunos de mis otros conocimientos de programación más allá del Desarrollo Web, desde el más nuevo hasta el más antiguo.",
      "other-backend-desc": "C# (.NET), C, Java (SpringBoot, Maven, Eclipse, Swing), Kotlin, PHP (Laravel, PDO), Python (FastAPI), SQL (MySQL, PostGres, SQLite), NoSQL (Firebase, MongoDB), Node (Next, Express) y paradigmas de POO, TDD, etc.",
      "other-frontend-desc": "Conocimiento intermedio <br> HTML (Semántico), CSS (Bootstrap, Materialize, TailWind, SASS), JS Vanilla, Node (React, Vue)",
      "other-edition-title": "Otros",
      "other-edition-desc": "Conocimiento en Machine Learning (IA), edición, aplicaciones (Paquete Office, Trello, Figma), Ingeniería de Software, etc.",
      "other-projects-title": "PROYECTOS",
      "other-projects-list": `<span>HTML,CSS,JS: </span> <a href="https://github.com/GustavoPereira-Dev/Hangman">Hangman</a> , <a href="https://github.com/GustavoPereira-Dev/AtividadeCSS3">Zoo Site</a><br><br><span>Node (NPM): </span> <a href="https://github.com/GustavoPereira-Dev/Projeto-Alura">Proyecto-Alura</a>, <a href=""></a><br><br><span>PHP: </span> <a href="https://github.com/GustavoPereira-Dev/SPTransAPI-busSearch">Olho Vivo Bus Search</a>, <a href="https://github.com/GustavoPereira-Dev/digitalcep">Digital CEP</a>,  <a href="https://github.com/GustavoPereira-Dev/ProjCarrosPHP">Project Car</a>,<br><br><span>Python:</span> <a href="https://github.com/GustavoPereira-Dev/Bootcamp-Python-Vivo">Bootcamp-Vivo</a>, <a href="https://github.com/GustavoPereira-Dev/Exercs-Python">Ejercicios de Python</a><br><br><span>C#: </span> <a href="https://github.com/GustavoPereira-Dev/trilha-net-teste-unitarios-desafio">Pruebas unitarias</a>(usando Xunit), <a href="https://github.com/GustavoPereira-Dev/trilha-net-poo-desafio">OOP in CSharp</a>,<a href="https://github.com/GustavoPereira-Dev/trilha-net-fundamentos-desafio">Fundamentals</a><br><br><span>Java: </span> <a href="https://github.com/GustavoPereira-Dev/Bootcamp-Santander-2024-BackEnd-Java">Bootcamp Santander</a>, <a href="https://github.com/GustavoPereira-Dev/Atividades-Java-LP">Actividades LP</a>,  <a href="https://github.com/GustavoPereira-Dev/Projeto-Eletrodomesticos-Java">Proyecto Electrodomésticos</a>,<a href="https://github.com/GustavoPereira-Dev/Projeto-OO-Java">Reino animal</a>, <a href="https://github.com/GustavoPereira-Dev/AtividadeJogoCorrida">Carrera de coches</a><br><br><span>Kotlin: </span> <a href="https://github.com/GustavoPereira-Dev/Navigation-Compose">Navigation Compose</a>, <a href="https://github.com/GustavoPereira-Dev/TaskTodayApp">TaskTodayApp</a>, <a href="https://github.com/GustavoPereira-Dev/Calculator-Jetpack-Compose">Calculadora Compose</a>,<a href="https://github.com/GustavoPereira-Dev/Learning-Jetback-Compose">Learning Compose</a>,<a href="https://github.com/GustavoPereira-Dev/Android-Aplication-Compose">Android Aplication</a>, <a href=""></a><br><br><span>Otros: </span> <a href="https://github.com/GustavoPereira-Dev/lab-natty-or-not">Fake Natty or not</a><a href="https://github.com/GustavoPereira-Dev/Generative-AI-In-Microsoft">Generative AI in Microsoft</a>, <a href="https://github.com/GustavoPereira-Dev/Cognitive-Search-in-Azure-ML">Cognitive Search</a>, <a href="https://github.com/GustavoPereira-Dev/Natural-Language-in-Azure-ML"> Natural Language Azure</a>,<a href="https://github.com/GustavoPereira-Dev/Computer-Vision-in-Azure-ML"> Computer Vision</a>, <a href="https://github.com/GustavoPereira-Dev/Machine-Learning-in-Azure-ML">Machine Learning</a>, <a href="https://github.com/GustavoPereira-Dev/dio-lab-open-source">Contribuciones en Github</a>`,
  }
};

export function translate(lang) {
  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(element => {
      const key = element.getAttribute('data-i18n');
      if (translations[lang] && translations[lang][key]) {
          if (element.tagName === 'INPUT' && element.type !== 'submit') {
              element.placeholder = translations[lang][key];
          } else if (element.tagName === 'INPUT' && element.type === 'submit') {
              element.value = translations[lang][key];
          } else if (element.tagName === 'TEXTAREA') {
              element.placeholder = translations[lang][key];
          } else {
              element.innerHTML = translations[lang][key];
          }
      }
  });
}